---
title: "Polynomials"
author: "Aathreya Kadambi"
date: "February 27, 2024"
header-includes:
- \usepackage{NotesTemplateF}
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: show
  pdf_document: default
---

<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
    body { 
      background-color: rgb(224, 244, 255); 
      font-family: Montserrat;
    }
    .toc-content { 
      height: 100%;
      background-color: white; 
    }
</style>


I was originally going to start this blog post like this:

Recently, I read a post from <a href="https://terrytao.wordpress.com/2023/08/25/yonedas-lemma-as-an-identification-of-form-and-function-the-case-study-of-polynomials/">Terrance Tao's blog on the Yoneda Lemma</a> which revived my interest in polynomials. I've also been seeing polynomials a lot in my algorithms class as we study FFTs. I really like polynomials, so I decided to dedicate this blog post to a thorough investigation of them. I chose to use an R markdown notebook because in my opinion it has the cleanest integration between LaTeX, HTML, and a powerful programming language I can use for implementations.

But then, I was delighted to find in my algebra PSet something called Pontryagin Duality, which is apparently related to FFT! So I had to remodel this blog post.

## Introduction

To start, I'll summarize a lot of the notation and results we'll need. This can be freely skipped if you're confident in your background on polynomials, and proofs are found in the appendix.

<b>Definition (Integer Polynomial).</b> A *polynomial* is an expression of the form $f(x) = a_0 + a_1 x + a_2 x^2 + \dots + a_n x^n$ for some nonnegative integer $n$ and integers $a_0$, $a_1$, ... which are called *coefficients* of $f$.

Some may be more familiar with a more general definition of polynomial (like the one used in Lang's *Algebra*), where instead of having integer coefficients we can have coefficients in any ring $R$. 

One big idea about polynomials is how to represent them. There is a very useful theorem which we call Lagrange interpolation. I will give the statement of this theorem from the original place I learned it, <a href="https://yufeizhao.com/olympiad/imo2008/zhao-polynomials.pdf">a note by Yufei Zhao:</a>

**Theorem (Lagrange Interpolation).** If $(x_1,y_1), \dots, (x_n,y_n)$ are points in the plane with distinct $x$-coordinates, then there exists a unique polynomial $P(x)$ of degree at most $n-1$ passing through these points, and it is given by the expression
  $$P(x) = \sum_{i=1}^n y_i \prod_{j\neq i} \dfrac{x - x_j}{x_i - x_j}.$$


Notice also that given values $\{x_1,\dots, x_n\}$, a polynomial $P$ gives us a collection of points $(x_1,P(x_1)), \dots, (x_n, P(x_n))$. As such, for any selection of points $\{x_1,\dots, x_n\}$, there is a correspondence between polynomials $P$ of degree at most $n-1$ and "$y$-values" $y_1,\dots, y_n$. 

## Fast Fourier Transform



## Yoneda Lemma

## Are These Related?

## Pontryagin Duality: A thing that sounds unbelievably cool and actually is unbelievably cool

To my surprise

## Vandermonde Matrices

## Geometric Insights

## Power Series and Generating Functions

Generating functions seem to be the "dual" notion to regular functions under the Fourier transformation. For example, the coefficients of the generating functions are the evaluations of another function, so it is as if we took the evaluation representation of another function and interpreted it as a coefficient representation. This gets us very interesting results which might give us amazing information about our original function. For example, interpretting the FFT of an indicator function as a coefficient representation is particularly useful, because then raising this new function to large powers can give us back distributions of sums of the indicator. Things like that.

## Appendix: Proofs

## Appendix: Other Nice Things

### Catalan Numbers


### Notes on Control Theory from CS 170 Discussion

- You have a dynamical system that you want to control
- How can I control the dynamical system
- AV [MPC]: 
  - $X_t$: State, $\{X_t \in \mathbb{R}^d\}$}
  - $U_t$: Control signal
  - $X_t$ might be your velocity, axxeleration, angular velocity, etc.
  - $U_t$ is like acceleration, breaking, etc..
  - Let's say you want to go from $A$ to $B$. we say that the next state $X_{t+1} = f(X_t, U_t)$. We want to find this optimal thing. We say that $U_{t+1} = g(X_{t+1})$
  - Thsee systems of equaions are called the governing dynamics, and you have some cost function, like mainly your travel time. You want to optimizze this cost function. 
