---
title: "A Column of Ones"
author: "Aathreya Kadambi"
date: "February 24, 2024"
header-includes:
- \usepackage{NotesTemplateF}
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: show
  pdf_document: default
---

<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
    body { 
      background-color: rgb(224, 244, 255); 
      font-family: Montserrat;
    }
    .toc-content { 
      height: 100%;
      background-color: white; 
    }
</style>


It's been a recurring theme for me that it can be a really good idea to add a column of ones. For example, in computer graphics, we often do projection transformations by appending a column of ones to our matrix to account for perspective. In regression, it's common practice to append a column of ones so that we can think of regression with an intercept and a slope as a special case of regression with just a slope. Now I want to try and investigate these ideas as an application of embedding ones' space into a larger projective space before doing some transformations, and then mapping back into our original space, and see what the true power of this idea is. I want to investigate the broader class of transformations we can achieve with this idea, and determine what power it holds in understanding things geometrically.

## Game Programming

## Regression

## Conclusions

