---
title: "Filtering and Smoothness"
author: "Aathreya Kadambi"
date: "February 24, 2024"
header-includes:
- \usepackage{NotesTemplateF}
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: show
  pdf_document: default
---

<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
    body { 
      background-color: rgb(224, 244, 255); 
      font-family: Montserrat;
    }
    .toc-content { 
      height: 100%;
      background-color: white; 
    }
</style>


I've been wondering how we can understand filtering and smoothness; especially in a discrete setting, what does *smoothness* really mean? In the continuous case, we might talk about a curve being $C^1$ or $C^n$ or $C^\infty$. But these ideas don't seem to have a direct implication in the discrete case. In this post, I want to consider how to measure smoothness for the discrete/digital case, and see the implications of this in the context of filtering methods. I'll first consider some ideas I can think of myself, and then consider methods others have come up with by asking Google and ChatGPT for suggestions on measuring smoothness in this discrete case.

## Finite/Discrete Differences



## A Topological Viewpoint

I have to acknowledge that my understanding of topology right now is somewhat limited, but I thought it would still be fun to try and apply what I do know. 


## Asking Google and ChatGPT


## More Tangible Experiments

