'use client'

import Image from 'next/image'
import Link from 'next/link'
import React, { useEffect } from 'react';

export default function Page() {

    useEffect(() => {
        if (typeof window !== 'undefined' && window.MathJax) {
          // Tell MathJax to typeset the page again
          window.MathJax.typeset();
        }
      });

    const latex_content_1 = { 
        __html: String.raw`The integers \(\mathbb{Z}\) form a group with respect to addition, with identity 0, and the inverse of \(x\) being denoted \(-x\). In a sense, I think that in some sense it is fair to think of \(\mathbb{Z}\) being the &quot;completion&quot; or &quot;closure&quot; of the natural numbers (including zero) with respect to inverses, noting that \(\mathbb{N}\) forms a monoid. It also turns out that \(\mathbb{Z}\) is the smallest ring containing \(\mathbb{N}\).`
    };

    const latex_content_2 = { 
        __html: String.raw`The only subgroups of \(\mathbb{Z}\) are sets of the form \((k) = \{kn : n \in \mathbb{Z}\}\), and it is clear that with \((1) = \mathbb{Z}\), \(a\) divides \(b\) is equivalent to \((b) \le (a)\) (\(\le\) denoting subgroup). In other words, the lattice of \(\mathbb{Z}\) is precisely the same as \(\mathbb{Z}\) considered as a poset with divisibility as the order. The centralizer and normalizer are trivially all of \(\mathbb{Z}\) since \(\mathbb{Z}\) is commutative.`
    };

    const latex_content_3 = { 
        __html: String.raw`Now I would like to categorize normal subgroups and group homomorphisms to and from \(\mathbb{Z}\). All subgroups are trivially normal since \(\mathbb{Z}\) is commutative. Additionally, it is interesting that every group homomorphism \(\varphi : \mathbb{Z} \rightarrow G\) is of the form \(1 \mapsto g\), so that \(n \mapsto g^n\). In this way the collection of homomorphisms from \(\mathbb{Z}\) to a group \(G\) appear to give us all cyclic subgroups of \(G\). Now we can define \(\text{ord}(g)\) to be the order of the cyclic subgroup generated by \(g\), and we see that now the kernel is precisely \((\text{ord}(g))\) and \(\text{im}(\varphi) \cong \mathbb{Z}/(\text{ord}(g))\).`
    };

    const proposition_1 = {
        __html: String.raw`` 
    };

    return (
        <main>
            <Link href="/orange-juice/sketches/"><i>See all sketches...</i></Link>
            <h1 className="title">Sketch 1</h1>
                <p><b>Examples of groups and their properties</b></p>
                <hr/>
                <h2>Huh...</h2>
                <p>it seems like <i>groups</i> are super interesting, and I still don&apos;t know them like the back of my hand. That&apos;s why this sketch is dedicated to them.</p>

                <p>
                    <b>Date Started:</b> December 29, 2023<br />
                    <b>Date Finished:</b> <i>Unfinished</i>
                </p>

                <h2>A list of groups to consider...</h2>
                <p>I studied much of what I know about algebra from Dummit and Foote as well as Lang, so many of the examples I will think of were inspired by these sources. If anyone has other ideas of useful groups to consider, contact me, I would love to learn to sketch them.</p>
                
                <dl>
                    <dd><Link href="#infinites">Integers, Rational Numbers, Real Numbers</Link></dd>
                    <dd><Link href="#residues">Residues modulo \(n\)</Link></dd>
                    <dd><Link href="#dihedral">Dihedral group</Link></dd>
                    <dd><Link href="#quaternion">Quaternions</Link></dd>
                    <dd><Link href="#klein-4">Klein-4 Group</Link></dd>
                    <dd><Link href="#symmetric">\(S_n\)</Link></dd>
                    <dd><Link href="#alternating">\(A_n\)</Link></dd>
                    <dd><Link href="#matrices">Matrices</Link></dd>
                </dl>

                <h2 id="infinities">Infinite Groups</h2>

                <p>This section covers mainly integers, rational numbers, and real numbers. While not present in this section, I will also treat infinite matrices in the infinite matrices section as an example of an infinite noncommutative group.</p>

                <h3>Integers</h3>

                <p dangerouslySetInnerHTML={latex_content_1}></p>

                <p dangerouslySetInnerHTML={latex_content_2}></p>

                <p dangerouslySetInnerHTML={latex_content_3}></p>
                
                <p><b>Proposition 1.</b> <div dangerouslySetInnerHTML={proposition_1}></div></p>

        </main>
    );
}
